### PR TITLE
Create qspec.codesnippet

### PR DESCRIPTION
**Pull request by jasonm23**
Add a snippet to create a QuickSpec stub

[✓] Tested on XCode 12 and 13

### CODE REVIEW

**Comment by jasonm23** [comment]
```
import Quick
import Nimble

class <#Subject#>Spec: QuickSpec {
    override func spec() {
        describe("<#Subject#>") {
            <#code#>
        }
    }
}

**Comment by jasonm23** [comment]
Wish I knew how to do mirrored fields, seems silly entering _Subject_ twice

**Comment by younata** [comment]
Thanks for doing this!

**Comment by jasonm23** [comment]
You're welcome.

I'll be scraping the nimble source to make a more complete set of snippets.  I often forget about some of them.

**Pull request merged**
